# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'piperchat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for piperchat

  platform :ios, '9.0'
  pod 'GoogleWebRTC'

  target 'piperchatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'piperchat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for piperchat-tvOS

  target 'piperchat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
